# Generated by Django 2.1 on 2018-08-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(null=True, upload_to='pic_folder/'),
        ),
    ]
