# Generated by Django 2.1 on 2018-08-26 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_user_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.FileField(null=True, upload_to='pic_folder/', validators=[django.core.validators.FileExtensionValidator(['JPEG'])]),
        ),
    ]
