# Generated by Django 2.1 on 2018-09-03 12:47

from django.db import migrations, models
import gateway.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20180826_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.FileField(null=True, upload_to='zibal/gateway/pic_folder/', validators=[gateway.validators.validate_file_extension]),
        ),
    ]
